// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendProject.Database;

namespace backendProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190524192451_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("backendProject.Database.Tables.Admin", b =>
                {
                    b.Property<Guid>("UniqueId");

                    b.HasKey("UniqueId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("backendProject.Database.Tables.Identity", b =>
                {
                    b.Property<string>("SubjectId");

                    b.Property<string>("Issuer");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SubjectId", "Issuer");

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("backendProject.Database.Tables.Profile", b =>
                {
                    b.Property<Guid>("UniqueId");

                    b.Property<long?>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Picture");

                    b.HasKey("UniqueId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("backendProject.Database.Tables.RefreshToken", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresUtc");

                    b.Property<string>("IdentityIssuer");

                    b.Property<string>("IdentitySubjectId");

                    b.Property<DateTime>("IssuedUtc");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Token");

                    b.HasIndex("IdentitySubjectId", "IdentityIssuer");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("backendProject.Database.Tables.Admin", b =>
                {
                    b.HasOne("backendProject.Database.Tables.Identity", "Identity")
                        .WithOne("Admin")
                        .HasForeignKey("backendProject.Database.Tables.Admin", "UniqueId")
                        .HasPrincipalKey("backendProject.Database.Tables.Identity", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backendProject.Database.Tables.Profile", b =>
                {
                    b.HasOne("backendProject.Database.Tables.Identity", "Identity")
                        .WithOne("Profile")
                        .HasForeignKey("backendProject.Database.Tables.Profile", "UniqueId")
                        .HasPrincipalKey("backendProject.Database.Tables.Identity", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backendProject.Database.Tables.RefreshToken", b =>
                {
                    b.HasOne("backendProject.Database.Tables.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentitySubjectId", "IdentityIssuer");
                });
#pragma warning restore 612, 618
        }
    }
}
