// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Backend.Database;

namespace Project.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191018162431_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project.Backend.Database.AccountTables.Identity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Issuer")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("SubjectId", "Issuer");

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("Project.Backend.Database.AccountTables.Profile", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext");

                    b.HasKey("UniqueId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Project.Backend.Database.AccountTables.RefreshToken", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IssuedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Token");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Project.Backend.Database.AccountTables.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FirstLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("IdentityUniqueId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("char(36)");

                    b.HasKey("SessionId");

                    b.HasIndex("IdentityUniqueId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Project.Backend.Database.AdminTables.Admin", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .HasColumnType("char(36)");

                    b.HasKey("UniqueId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Project.Backend.Database.FilesTables.File", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FileLength")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnedByUniqueId")
                        .HasColumnType("char(36)");

                    b.HasKey("FileId");

                    b.HasIndex("OwnedByUniqueId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("Project.Backend.Database.FilesTables.Read", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SharedByIdentityUniqueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SharedByUniqueId")
                        .HasColumnType("char(36)");

                    b.HasKey("FileId", "UniqueId");

                    b.HasIndex("SharedByIdentityUniqueId");

                    b.HasIndex("UniqueId");

                    b.ToTable("ReadPermissions");
                });

            modelBuilder.Entity("Project.Backend.Database.FilesTables.Write", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SharedByIdentityUniqueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SharedByUniqueId")
                        .HasColumnType("char(36)");

                    b.HasKey("FileId", "UniqueId");

                    b.HasIndex("SharedByIdentityUniqueId");

                    b.HasIndex("UniqueId");

                    b.ToTable("WritePermissions");
                });

            modelBuilder.Entity("Project.Backend.Database.AccountTables.Profile", b =>
                {
                    b.HasOne("Project.Backend.Database.AccountTables.Identity", "Identity")
                        .WithOne("Profile")
                        .HasForeignKey("Project.Backend.Database.AccountTables.Profile", "UniqueId")
                        .HasPrincipalKey("Project.Backend.Database.AccountTables.Identity", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Backend.Database.AccountTables.RefreshToken", b =>
                {
                    b.HasOne("Project.Backend.Database.AccountTables.Session", "Session")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Project.Backend.Database.AccountTables.RefreshToken", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Backend.Database.AccountTables.Session", b =>
                {
                    b.HasOne("Project.Backend.Database.AccountTables.Identity", "Identity")
                        .WithMany("Sessions")
                        .HasForeignKey("IdentityUniqueId")
                        .HasPrincipalKey("UniqueId");
                });

            modelBuilder.Entity("Project.Backend.Database.AdminTables.Admin", b =>
                {
                    b.HasOne("Project.Backend.Database.AccountTables.Identity", "Identity")
                        .WithOne("Admin")
                        .HasForeignKey("Project.Backend.Database.AdminTables.Admin", "UniqueId")
                        .HasPrincipalKey("Project.Backend.Database.AccountTables.Identity", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Backend.Database.FilesTables.File", b =>
                {
                    b.HasOne("Project.Backend.Database.AccountTables.Profile", "OwnedBy")
                        .WithMany("OwnedByMe")
                        .HasForeignKey("OwnedByUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Backend.Database.FilesTables.Read", b =>
                {
                    b.HasOne("Project.Backend.Database.FilesTables.File", "File")
                        .WithMany("ReadPermissions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Backend.Database.AccountTables.Identity", "SharedByIdentity")
                        .WithMany("SharedByMeReadPermissions")
                        .HasForeignKey("SharedByIdentityUniqueId")
                        .HasPrincipalKey("UniqueId");

                    b.HasOne("Project.Backend.Database.AccountTables.Identity", "Identity")
                        .WithMany("ReadPermissions")
                        .HasForeignKey("UniqueId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Backend.Database.FilesTables.Write", b =>
                {
                    b.HasOne("Project.Backend.Database.FilesTables.File", "File")
                        .WithMany("WritePermissions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Backend.Database.AccountTables.Identity", "SharedByIdentity")
                        .WithMany("SharedByMeWritePermissions")
                        .HasForeignKey("SharedByIdentityUniqueId")
                        .HasPrincipalKey("UniqueId");

                    b.HasOne("Project.Backend.Database.AccountTables.Identity", "Identity")
                        .WithMany("WritePermissions")
                        .HasForeignKey("UniqueId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
