// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendProject.Data;

namespace backendProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("backendProject.Data.Tables.Identity", b =>
                {
                    b.Property<string>("SubjectId");

                    b.Property<string>("Issuer");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SubjectId", "Issuer");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("backendProject.Data.Tables.Profile", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Picture");

                    b.HasKey("UniqueId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("backendProject.Data.Tables.RefreshToken", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresUtc");

                    b.Property<string>("IdentityIssuer");

                    b.Property<string>("IdentitySubjectId");

                    b.Property<DateTime>("IssuedUtc");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Token");

                    b.HasIndex("IdentitySubjectId", "IdentityIssuer");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("backendProject.Data.Tables.Identity", b =>
                {
                    b.HasOne("backendProject.Data.Tables.Profile", "Profile")
                        .WithOne("Identity")
                        .HasForeignKey("backendProject.Data.Tables.Identity", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backendProject.Data.Tables.RefreshToken", b =>
                {
                    b.HasOne("backendProject.Data.Tables.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentitySubjectId", "IdentityIssuer");
                });
#pragma warning restore 612, 618
        }
    }
}
